
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author comp
 */
public class AdminMainPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainPage
     */
    private static ArrayList<productModel> productInformationList;
    private static ArrayList<ClientModel> userInformationList;
    
    static int flag=0;
    
    public AdminMainPage() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize);
        this.insertCustomerDetails();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        customerDetails = new javax.swing.JLabel();
        productDetails = new javax.swing.JLabel();
        AddItem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        customerDetails.setBackground(new java.awt.Color(153, 204, 255));
        customerDetails.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        customerDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerDetails.setText("Customer Details");
        customerDetails.setAlignmentX(0.5F);
        customerDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        customerDetails.setOpaque(true);
        customerDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerDetailsMousePressed(evt);
            }
        });

        productDetails.setBackground(new java.awt.Color(153, 204, 255));
        productDetails.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        productDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productDetails.setText("Product Details");
        productDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productDetails.setOpaque(true);
        productDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productDetailsMousePressed(evt);
            }
        });

        AddItem.setBackground(new java.awt.Color(0, 204, 204));
        AddItem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AddItem.setText("Add Item");
        AddItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainTable.setBackground(new java.awt.Color(255, 204, 204));
        mainTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mainTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mainTable.setGridColor(new java.awt.Color(0, 0, 0));
        mainTable.setRowHeight(30);
        mainTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mainTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static ArrayList <productModel> getProductList()
    {
        return  productInformationList;
    }
    
     public static ArrayList <ClientModel> getUserInformationList()
    {
        return  userInformationList;
    }
    
    private void insertCustomerDetails()
    {
        this.flag=1;
         DefaultTableModel dtModel = (DefaultTableModel) mainTable.getModel();
        int rowCount = dtModel.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
                dtModel.removeRow(i);
        }
        userInformationList=new ArrayList<>();
        userInformationList=loginDatabase.getAllUserInformation();
        
        String header[] = {"Name", "User Name", "Mobile","Image"};
        for(int i=0;i<mainTable.getColumnCount();i++)
        {
            TableColumn column1 = mainTable.getTableHeader().getColumnModel().getColumn(i);
            column1.setHeaderValue(header[i]);
        } 
        
        for(int i=0;i<userInformationList.size();i++){
            String name=userInformationList.get(i).getName();
            String userName=userInformationList.get(i).getUserName();
            String mobile=userInformationList.get(i).getMobile();
            String imagePath=userInformationList.get(i).getImagePath();

            //Icon icon = new ImageIcon(getClass().getResource("C:\\Users\\Mayank\\Desktop\\project\\download.jpg")); 
            //JLabel label = new JLabel();
            //label.setIcon(icon);
            dtModel.addRow(new Object[]{name,userName,mobile,imagePath});
        }
  //      mainTable.getColumn("Photo").setCellRenderer(new ImageRenderer());
        System.out.println("Helo");
    }
    private void customerDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerDetailsMousePressed
        
        insertCustomerDetails();
       
    }//GEN-LAST:event_customerDetailsMousePressed

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        
    }//GEN-LAST:event_jPanel2KeyPressed

    private void productDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsMousePressed
        
        this.flag=0;
         DefaultTableModel dtModel = (DefaultTableModel) mainTable.getModel();
        int rowCount = dtModel.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
                dtModel.removeRow(i);
        }
        String header[] = {"Product Id", "Name", "Price","Image"};
        for(int i=0;i<mainTable.getColumnCount();i++)
        {
            TableColumn column1 = mainTable.getTableHeader().getColumnModel().getColumn(i);
            column1.setHeaderValue(header[i]);
        } 
         productInformationList=new ArrayList<>();
        productInformationList=itemDatabase.getAllProductInformation();
        for(int i=0;i<productInformationList.size();i++){
            String name=productInformationList.get(i).getName();
            int productId=productInformationList.get(i).getProductId();
            int price=productInformationList.get(i).getPrice();
            String imagePath=productInformationList.get(i).getImagePath();

           // Icon icon = new ImageIcon(getClass().getResource("C:\\Users\\Mayank\\Desktop\\project\\download.jpg")); 
            //JLabel label = new JLabel();
            //label.setIcon(icon);
            dtModel.addRow(new Object[]{Integer.toString(productId),name,Integer.toString(price),imagePath});
        }
  //      mainTable.getColumn("Photo").setCellRenderer(new ImageRenderer());
        System.out.println("Helo");
    }//GEN-LAST:event_productDetailsMousePressed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void mainTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainTableMouseClicked
        int row=mainTable.getSelectedRow();
        
        this.dispose();
        if(flag==0)
        {
            try {
                     new ProductDetail(row).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(AdminMainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            new MyAccount(row).setVisible(true);
            
        }
        
    }//GEN-LAST:event_mainTableMouseClicked

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed

        new serverAddItem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminMainPage obj=new AdminMainPage();
                obj.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem;
    private javax.swing.JLabel customerDetails;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JLabel productDetails;
    // End of variables declaration//GEN-END:variables
}
